version: '3.8'

services:
  postgres_db:
    image: postgres:latest
    container_name: bas_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: BusinessAnalyticsDB
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  # Трейсинг (Zipkin)
  zipkin:
    image: openzipkin/zipkin
    container_name: bas_zipkin
    ports:
      - "9411:9411"
    networks:
      - bas_network

  # Збір метрик (Prometheus)
  prometheus:
    image: prom/prometheus
    container_name: bas_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - bas_network

  # Візуалізація (Grafana)
  grafana:
    image: grafana/grafana
    container_name: bas_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - bas_network

  # База для результатів навантажувального тестування (InfluxDB)
  influxdb:
    image: influxdb:1.8
    container_name: bas_influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=jmeter
    networks:
      - bas_network

  # Аналіз коду (SonarQube)
  sonarqube:
    image: sonarqube:community
    container_name: bas_sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    networks:
      - bas_network

volumes:
  postgres_data:

networks:
  bas_network:
    driver: bridge